services:
  # nuxt:
  #   build: ./nuxt
  #   expose:
  #     - 3000
  #   restart: always

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    expose:
      - 3001
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
    ports:
      - 5000
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345
      PMA_ARBITRARY: 1

  nginx:
    depends_on:
      # - nuxt
      - nestjs
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx/
    restart: always
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'
    restart: always
  
  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  db_data:
  minio_data:
    driver: local
